property:
  purchase_price: 200000
  gross_rental_income_per_month: 500
  energy_efficiency_class: A
  last_renovated: 2023-01-01
  location: Hamburg Allermoehe
  loan_details:
    loan_term_years: 30
    down_payment: 0.018
    loan_interest_rate: 0.04
  operating_expenses_per_month:
    property_management: 200
    maintenance: 100
    insurance: 100
    property_taxes: 150
